server:
  # Puerto de escucha del BFF
  port: 8080

spring:
  application:
    name: bff-gateway

# Configuración del Cliente Eureka para auto-registro
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Configuración detallada del Circuit Breaker con Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      kpiService:
        # Tipo de ventana deslizante
        slidingWindowType: COUNT_BASED
        # Tamaño de la ventana deslizante
        slidingWindowSize: 10
        # Umbral de tasa de fallos: 50%
        failureRateThreshold: 50
        # Umbral de llamadas lentas: 75%
        slowCallRateThreshold: 75
        # Duración límite de una llamada lenta: 2 segundos
        slowCallDurationThreshold: 2000
        # Tiempo de espera en estado ABIERTO: 30 segundos
        waitDurationInOpenState: 30000
        # Cantidad de llamadas de prueba permitidas en estado SEMI-ABIERTO
        permittedNumberOfCallsInHalfOpenState: 5
        # Transición automática de abierto a semi-abierto
        automaticTransitionFromOpenToHalfOpenEnabled: true

# Configuración de Actuator para exponer métricas completas en el Dashboard de Spring Boot Admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
